[monitor:///var/audit/current]
disabled = false
sourcetype = auditd
index = macos

[monitor:///var/audit/*.log]
disabled = false
sourcetype = auditd
index = macos

[monitor:///var/audit/]
disabled = false
sourcetype = auditd
index = macos
